# Generated by Django 5.2.1 on 2025-05-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="generationalinsights",
            name="last_generated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
